### ISSUE TITLE
insurgent-lab

### ISSUE THREAD

**Issue by insurgent** [sheerlox/semantic-release-hex-demo#4]
Hi Pierre,

I just wanted to send you a note as I believe there's a mistake in your semantic-release-hex-demo project on Github that's notifying me (insurgent) instead of the user "Insurgent-lab".

Take care,
John

**Comment by sheerlox** [comment]
Hi :wave: 

This is because we use the package `@insurgent/conventional-changelog-preset`, where `@insurgent` is the name of the NPM org.

Due to a bug in that package, the org name inside the backtick quoted package's name from [this commit](https://github.com/sheerlox/semantic-release-hex-demo/commit/dffc963af48b296dc5c81d02cef2b00832aec218) got unquoted in the generated CHANGELOG, effectively tagging you because of a name collision.

Sorry for the unsolicited notification :sweat_smile: 

All the best,
Pierre

P.S. Don't hesitate to let me know if it happens again!
